syntax enable

syntax on

set guifont=Monaco\ 12

set history=2000

filetype on 

filetype indent on

filetype plugin on

filetype plugin indent on

set autoread

set mouse=a

set ruler

set showcmd

set showmode

set number

set nowrap

set tabstop=4

set shiftwidth=4

set et

set smarttab

set encoding=utf-8

syntax on
set nu!
set autoindent
set backspace=2
set ts=4 
set expandtab
set hlsearch
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

